packages:
  - ./
  - playground/

patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true

settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict 

catalog:
  "@alanscodelog/commitlint-config": ^3.1.2
  "@alanscodelog/eslint-config": ^6.3.1
  "@alanscodelog/semantic-release-config": ^6.0.0
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.2
  "@alanscodelog/vite-config": ^0.0.6
  "@commitlint/cli": ^19.8.1
  "@faker-js/faker": ^10.0.0
  "@fortawesome/fontawesome-svg-core": ^7.0.1
  "@fortawesome/free-brands-svg-icons": ^7.0.1
  "@fortawesome/free-regular-svg-icons": ^7.0.1
  "@fortawesome/free-solid-svg-icons": ^7.0.1
  "@iconify/json": ^2.2.385
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.1.2
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.1.2
  "@nuxt/types": ^2.18.1
  "@playwright/test": =1.56.0
  "@rollup/plugin-dynamic-import-vars": ^2.1.5
  "@tailwindcss/cli": ^4.1.13
  "@tailwindcss/vite": ^4.1.13
  "@testing-library/vue": ^8.1.0
  "@tiptap/core": ^3.4.2
  "@tiptap/extension-blockquote": ^3.4.2
  "@tiptap/extension-bold": ^3.4.2
  "@tiptap/extension-code": ^3.4.2
  "@tiptap/extension-code-block": ^3.4.2
  "@tiptap/extension-code-block-lowlight": ^3.4.2
  "@tiptap/extension-dropcursor": ^3.4.2
  "@tiptap/extension-gapcursor": ^3.4.2
  "@tiptap/extension-hard-break": ^3.4.2
  "@tiptap/extension-heading": ^3.4.2
  "@tiptap/extension-highlight": ^3.4.2
  "@tiptap/extension-history": ^3.4.2
  "@tiptap/extension-image": ^3.4.2
  "@tiptap/extension-italic": ^3.4.2
  "@tiptap/extension-link": ^3.4.2
  "@tiptap/extension-paragraph": ^3.4.2
  "@tiptap/extension-strike": ^3.4.2
  "@tiptap/extension-subscript": ^3.4.2
  "@tiptap/extension-superscript": ^3.4.2
  "@tiptap/extension-table": ^3.4.2
  "@tiptap/extension-table-cell": ^3.4.2
  "@tiptap/extension-table-header": ^3.4.2
  "@tiptap/extension-table-row": ^3.4.2
  "@tiptap/extension-text": ^3.4.2
  "@tiptap/extension-underline": ^3.4.2
  "@tiptap/html": ^3.4.2
  "@tiptap/pm": ^3.4.2
  "@tiptap/vue-3": ^3.4.2
  "@types/node": ^24.5.1
  "@vitejs/plugin-vue": ^6.0.1
  "@vitest/browser": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  "@witchcraft/nuxt-utils": ^0.3.6
  "@witchcraft/ui": ^0.3.7
  colord: ^2.9.3
  concurrently: ^9.2.1
  cross-env: ^10.0.0
  defu: ^6.1.4
  eslint: ^9.35.0
  fast-glob: ^3.3.3
  highlight.js: ^11.11.1
  http-server: ^14.1.1
  husky: ^9.1.7
  lowlight: ^3.3.0
  madge: ^8.0.0
  metamorphosis: ^0.6.1
  mime: ^4.1.0
  nanoid: ^5.1.5
  nuxt: ^4.1.2
  onchange: ^7.1.0
  playwright: =1.56.0
  playwright-core: =1.56.0
  prosemirror-test-builder: ^1.1.1
  radix-vue: ^1.9.17
  reka-ui: ^2.5.0
  semantic-release: ^24.2.8
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  typedoc: ^0.28.13
  typescript: ~5.9.2
  unplugin-icons: ^22.3.0
  unplugin-vue-components: ^29.1.0
  uuid: ^13.0.0
  vite: ^7.1.5
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-component-type-helpers: ^3.0.7
  vue-tsc: ^2.2.12
  y-prosemirror: ^1.3.7
  yjs: ^13.6.27
