name: Docs

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ docs ]

jobs:
  docs:
    if: "vars.ENABLE_DOCS == 'true'"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24.15.0']
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: alanscodelog/actions/.github/actions/setup@master
        with:
          USE_LOCKFILE: ${{ vars.USE_LOCKFILE }}
          INSTALL_PLAYWRIGHT: true

      - name: Build
        uses: alanscodelog/actions/.github/actions/build@master
        with:
          BUILD_PLAYGROUND: true

      - name: Deploy Docs
        uses: alanscodelog/actions/.github/actions/docs@master
        with:
          BUILD_PLAYGROUND: true
          BUILD_DEMO: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}